# Generated by Django 4.2.13 on 2024-07-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigreetingcards', '0002_alter_image_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
