# Generated by Django 4.2.13 on 2024-07-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigreetingcards', '0003_image_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
