# Generated by Django 4.2.13 on 2024-07-15 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aigreetingcards', '0004_alter_image_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='test',
        ),
    ]
