# Generated by Django 4.2.13 on 2024-07-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_card_last4_payment_cardholder_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
