# Generated by Django 4.2.13 on 2024-07-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_country_payment_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='billing_address',
        ),
        migrations.AlterField(
            model_name='payment',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
