# Generated by Django 4.2.13 on 2024-07-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('complete', 'Complete'), ('expired', 'Expired'), ('failed', 'Failed')], default='open', max_length=10),
        ),
    ]
