# ci.yml

name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/${{ secrets.POSTGRES_DB }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DJANGO_DEBUG: ${{ secrets.DJANGO_DEBUG }}
      DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      POSTGRES_HOST: localhost
      EMAIL_HOST: ${{secrets.EMAIL_HOST}}
      EMAIL_PORT: ${{secrets.EMAIL_PORT}}
      EMAIL_HOST_USER: ${{secrets.EMAIL_HOST_USER}}
      EMAIL_HOST_PASSWORD: ${{secrets.EMAIL_HOST_PASSWORD}}
      DEFAULT_FROM_EMAIL: ${{secrets.DEFAULT_FROM_EMAIL}}
      STRIPE_PUBLISHABLE_KEY:
      STRIPE_SECRET_KEY: ${{secrets.STRIPE_SECRET_KEY}}
      BACKEND_DOMAIN: ${{secrets.BACKEND_DOMAIN}}
      PAYMENT_SUCCESS_URL: ${{secrets.PAYMENT_SUCCESS_URL}}
      PAYMENT_CANCEL_URL: ${{secrets.PAYMENT_CANCEL_URL}}
      PAYMENT_WEBHOOK_URL: ${{secrets.PAYMENT_WEBHOOK_URL}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          pytest
